version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: yourname
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: bokapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
